name: release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3.0.0

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

  publish:
    name: Publish

    needs: build

    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3.0.0
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_ENV: development

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
